POST http://localhost:5000/api/searchProducts

{
  "category": "",
  "searchTerm": "find the best video game to gift to a teenager boy"
}

###

POST https://dab-sql-dab-api.jollystone-054ffb48.centralus.azurecontainerapps.io/api/searchProducts

{
  "category": "",
  "searchTerm": "find the best video game to gift to a teenager boy"
}
